### PR TITLE
Tests and documentation

### PR DESCRIPTION
**Pull request by Nikoleta-v3**
This `pr` is not ready to get merge.

I have included docstrings to `qlin.py` and `ncbitax.py`. I have also included tests for the files and for the `__init__.py`. 

**Regarding the `qlin.py` file.** I applied some changes to the implementation of the functions (please review). Some remaining thoughts are the following:

- `q` as an argument name is not very self explanatory. Should it be remained to `sname` for example?
- the same applied to `tq`. Should it be remained to `taxid`?
- I like the print statement but maybe we should also give the user the option to hide them. In the `qlin.py` for example. Should there be an argument to "hide" the output?

I will keep working on this 👍🏻 let me know what you think regarding the above.

### CODE REVIEW

**Comment by Nikoleta-v3** [comment]
Note to myself: add a file to invoke GitHub actions.

**Comment by kullrich** [comment]
Since the `qlin` is meant to show the user what the lineage of the query species is, the initial thaught of qlin was just this. So that the user will be aware of the query species lineage and the possible tree nodes that will occure in the resulting orthomap. Getting the qlin results back within a jupyter notebook just came later, to be able to provide the user with this information and directly access e.g. the `taxid`.

**Comment by Nikoleta-v3** [comment]
Cool, should I tweak the arguments names and include a "hide" functionality? what do you think?

**Comment by kullrich** [comment]
Yes, for the command_script I would like to keep it rather short, since for most users working with blast-like software tools and OrthoFinder the `q` for `query` and `qt` for `query taxid` should be fine and not too much to put on the command line for them.

**Review by kullrich — APPROVED** [review]

**Pull request merged**
