### PR TITLE
Implementing further tests

### PR DESCRIPTION
**Pull request by Nikoleta-v3**
There are currently a few functions that are not being tested. That is because I am not too sure to call them or because I am missing some data. 

Let's chat 👍🏻

### CODE REVIEW

**Comment by kullrich** [comment]
Thanks, I try to create a simple small example so that one could distribute with the pacakage and test all scenarios

**Comment by Nikoleta-v3** [comment]
Ah one of the tests failed because I only have the data file locally. It's the file:

 - 'ensembl_105_orthofinder_species_list.tsv'
 - 'ensembl_105_orthofinder_Orthogroups.GeneCount.tsv'
 - 'ensembl_105_orthofinder_Orthogroups.tsv'

Do you want me to push them under the folder examples @kullrich?

**Comment by kullrich** [comment]
Hi,
all files are here:
https://doi.org/10.5281/zenodo.7242263

The question is if we put it in PyPi how big the files are allowed to be or if we would need to create a python load function for examples, like e.g.: here:

https://scanpy.readthedocs.io/en/stable/generated/scanpy.datasets.pbmc3k.html#scanpy.datasets.pbmc3k

**Comment by kullrich** [comment]
So `orthomap.datasets.ensembl105` to load them?

**Comment by kullrich** [comment]
https://github.com/scverse/scanpy/blob/master/scanpy/datasets/_datasets.py

**Pull request merged**
